apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ckan-storage
  name: ckan-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-dadosabertos-kube-l-pv
  volumeMode: Filesystem
status: {}
