apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: solr-data
  name: solr-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs-basedeconhecimento-kube-d-pv
  volumeMode: Filesystem
status: {}
